### ISSUE TITLE
Omnibus Roadmap

### ISSUE THREAD

**Issue by phobson** [hetland/pygridgen#15]
I've currently got separate (serially cut) branches for the following (check marks mean all tests are passing and I'm ready to submit a pull request):

 - [ ] DOC: adds fairly comprehensive documentation to the `Focus` and `Gridgen` classes
 - [ ] REF: moves to pyproj import to the `CGrid_geo` class to make basemap/pyproj truly optional
 - [ ] QA: adds several tests to the `Focus` and `_Focus_*` classes
 - [ ] REF/QA: refactors `_Focus_x` and `_Focus_y` into a single class with an `axis` attribute, while still passing all the tests previously set up. This removes the maintenance burden of the two very similar classes (recall there was earlier a bug in both)
 - [ ] ENH: Add an `autogen` kwarg to the `Gridgen` constructor. You can get it to `False` and postpone actually generating the grid. Not sure what motivated this. It just seemed nice.
 - [ ] ENH: Caching the `sigmas` values for reuse to significantly increase performance when interactively generating/tweaking/visualizing a new grid
 - [ ] ENH: Function to load boundary data (x, y, and beta) from shapefiles
 - [ ] ENH: Function to plot grids either as points or gridcells
 - [ ] ENH: Function to export grids as points (any of the attributes) or cells

Any interest in these?

(cc: @rsignell-usgs)

**Comment by phobson** [comment]
I've crossed out the bottom three enhancements, opting to place them in this module here:
https://github.com/phobson/pygridtools

Everything else is ready to go.

I have to say, caching the sigma values is **huge**. Iterating on a complex grid goes much much faster now.
